### PR TITLE
feat: validate ttl formats failing on API call

### PR DESCRIPTION
**Pull request by waxb**

### CODE REVIEW

**Review by kassianh — APPROVED** [review]
lgtm

**Review by soerenmartius — APPROVED** [review]
lgtm

**Review by zied-elouaer — APPROVED** [review]
LGTM

**Review by soerenmartius — COMMENTED** [review]
should we add this to the changelog?

**Comment by waxb** [comment]
> should we add this to the changelog?

i was thinking about the same and my opinion is that this PR doesn't introduce any functional change, only brings the runtime API validation a few steps closer to development, hence I'd release this with the next functional change.

@mariux what do you think about the validation blocks? i think this doesn't restrict anything that wouldn't be an error on `apply`, and if only introduces chore if the API changes which could do it anyway but helps keep the `plan` more reliable

**Pull request closed without merging**
